// swift-tools-version: 6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

// Source files curated from the 7zip submodule.
// Derived from Sources/CSevenZip/SOURCES.md -- update both together.
// swiftlint:disable:next blanket_disable_command
// swiftlint:disable file_length
let cSevenZipSources: [String] = [
    // C/ -- Base C utilities
    "Sources/CSevenZip/vendor/7zip/C/7zCrc.c",
    "Sources/CSevenZip/vendor/7zip/C/7zCrcOpt.c",
    "Sources/CSevenZip/vendor/7zip/C/Alloc.c",
    "Sources/CSevenZip/vendor/7zip/C/CpuArch.c",
    "Sources/CSevenZip/vendor/7zip/C/Delta.c",
    "Sources/CSevenZip/vendor/7zip/C/LzmaDec.c",
    "Sources/CSevenZip/vendor/7zip/C/Lzma2Dec.c",
    "Sources/CSevenZip/vendor/7zip/C/Lzma2DecMt.c",
    "Sources/CSevenZip/vendor/7zip/C/LzmaEnc.c",
    "Sources/CSevenZip/vendor/7zip/C/Lzma2Enc.c",
    "Sources/CSevenZip/vendor/7zip/C/LzFind.c",
    "Sources/CSevenZip/vendor/7zip/C/LzFindMt.c",
    "Sources/CSevenZip/vendor/7zip/C/LzFindOpt.c",
    "Sources/CSevenZip/vendor/7zip/C/7zAlloc.c",
    "Sources/CSevenZip/vendor/7zip/C/7zArcIn.c",
    "Sources/CSevenZip/vendor/7zip/C/7zBuf.c",
    "Sources/CSevenZip/vendor/7zip/C/7zBuf2.c",
    "Sources/CSevenZip/vendor/7zip/C/7zDec.c",
    "Sources/CSevenZip/vendor/7zip/C/7zFile.c",
    "Sources/CSevenZip/vendor/7zip/C/7zStream.c",
    "Sources/CSevenZip/vendor/7zip/C/Aes.c",
    "Sources/CSevenZip/vendor/7zip/C/AesOpt.c",
    "Sources/CSevenZip/vendor/7zip/C/Bcj2.c",
    "Sources/CSevenZip/vendor/7zip/C/Bcj2Enc.c",
    "Sources/CSevenZip/vendor/7zip/C/Blake2s.c",
    "Sources/CSevenZip/vendor/7zip/C/Bra.c",
    "Sources/CSevenZip/vendor/7zip/C/Bra86.c",
    "Sources/CSevenZip/vendor/7zip/C/BraIA64.c",
    "Sources/CSevenZip/vendor/7zip/C/BwtSort.c",
    "Sources/CSevenZip/vendor/7zip/C/DllSecur.c",
    "Sources/CSevenZip/vendor/7zip/C/HuffEnc.c",
    "Sources/CSevenZip/vendor/7zip/C/Lzma86Dec.c",
    "Sources/CSevenZip/vendor/7zip/C/Lzma86Enc.c",
    "Sources/CSevenZip/vendor/7zip/C/LzmaLib.c",
    "Sources/CSevenZip/vendor/7zip/C/Md5.c",
    "Sources/CSevenZip/vendor/7zip/C/MtCoder.c",
    "Sources/CSevenZip/vendor/7zip/C/MtDec.c",
    "Sources/CSevenZip/vendor/7zip/C/Ppmd7.c",
    "Sources/CSevenZip/vendor/7zip/C/Ppmd7aDec.c",
    "Sources/CSevenZip/vendor/7zip/C/Ppmd7Dec.c",
    "Sources/CSevenZip/vendor/7zip/C/Ppmd7Enc.c",
    "Sources/CSevenZip/vendor/7zip/C/Ppmd8.c",
    "Sources/CSevenZip/vendor/7zip/C/Ppmd8Dec.c",
    "Sources/CSevenZip/vendor/7zip/C/Ppmd8Enc.c",
    "Sources/CSevenZip/vendor/7zip/C/Sha1.c",
    "Sources/CSevenZip/vendor/7zip/C/Sha256.c",
    "Sources/CSevenZip/vendor/7zip/C/Sha3.c",
    "Sources/CSevenZip/vendor/7zip/C/Sha512.c",
    "Sources/CSevenZip/vendor/7zip/C/Sort.c",
    "Sources/CSevenZip/vendor/7zip/C/Threads.c",
    "Sources/CSevenZip/vendor/7zip/C/Xxh64.c",
    "Sources/CSevenZip/vendor/7zip/C/Xz.c",
    "Sources/CSevenZip/vendor/7zip/C/XzCrc64.c",
    "Sources/CSevenZip/vendor/7zip/C/XzCrc64Opt.c",
    "Sources/CSevenZip/vendor/7zip/C/XzDec.c",
    "Sources/CSevenZip/vendor/7zip/C/XzEnc.c",
    "Sources/CSevenZip/vendor/7zip/C/XzIn.c",
    "Sources/CSevenZip/vendor/7zip/C/ZstdDec.c",

    // CPP/Common/ -- Core C++ utilities
    "Sources/CSevenZip/vendor/7zip/CPP/Common/CRC.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/CrcReg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/IntToString.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/MyString.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/MyVector.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/MyXml.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/MyMap.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/NewHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/StringConvert.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/UTFConvert.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Wildcard.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/MyWindows.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/DynLimBuf.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/StringToInt.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/C_FileIO.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Sha256Prepare.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Sha1Prepare.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Sha512Prepare.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Sha1Reg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Sha256Reg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Sha3Reg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Sha512Reg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Md5Reg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/CksumReg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/XzCrc64Init.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/XzCrc64Reg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/Xxh64Reg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Common/LzFindPrepare.cpp",

    // CPP/Windows/ -- Windows API stubs for POSIX
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/FileDir.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/FileFind.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/FileIO.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/FileName.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/PropVariant.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/PropVariantConv.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/PropVariantUtils.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/Synchronization.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/System.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/SystemInfo.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/TimeUtils.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/FileLink.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/FileSystem.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/ErrorMsg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/Windows/DLL.cpp",

    // CPP/7zip/Common/ -- Stream interfaces
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/CreateCoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/CWrappers.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/FileStreams.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/FilterCoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/InBuffer.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/InOutTempBuffer.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/LimitedStreams.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/MethodId.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/MethodProps.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/OffsetStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/OutBuffer.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/ProgressUtils.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/PropId.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/StreamObjects.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/StreamUtils.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/UniqBlocks.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/VirtThread.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/FilePathAutoRename.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/LockedStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/MemBlocks.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/MultiOutStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/OutMemStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/ProgressMt.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Common/StreamBinder.cpp",

    // CPP/7zip/Archive/ -- Format handlers
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ArchiveExports.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/DllExports2.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/CoderMixer2.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/DummyOutStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/FindSignature.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/HandlerOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/InStreamWithCRC.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/ItemNameUtils.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/MultiStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/OutStreamWithCRC.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/OutStreamWithSha1.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Common/ParseProperties.cpp",

    // 7z format
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zDecode.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zExtract.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zHeader.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zProperties.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zSpecStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zCompressionMode.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zEncode.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zFolderInStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zHandlerOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/7z/7zUpdate.cpp",

    // Zip format
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipHandlerOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipItem.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipAddCommon.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Zip/ZipUpdate.cpp",

    // GZip, BZip2, Xz
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/GzHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Bz2Handler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/XzHandler.cpp",

    // Tar format
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Tar/TarHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Tar/TarHeader.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Tar/TarHandlerOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Tar/TarIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Tar/TarOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Tar/TarRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Tar/TarUpdate.cpp",

    // Rar format
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Rar/RarHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Rar/Rar5Handler.cpp",

    // Other archive handlers
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/LzmaHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/SplitHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/PpmdHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/HandlerCont.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/DeflateProps.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ZHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ZstdHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Cab/CabBlockInStream.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Cab/CabHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Cab/CabHeader.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Cab/CabIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Cab/CabRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Iso/IsoHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Iso/IsoHeader.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Iso/IsoIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Iso/IsoRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Nsis/NsisDecode.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Nsis/NsisHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Nsis/NsisIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Nsis/NsisRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Udf/UdfHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Udf/UdfIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Wim/WimHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Wim/WimHandlerOut.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Wim/WimIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Wim/WimRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/XarHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ArHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ArjHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Base64Handler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/CpioHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/CramfsHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/DmgHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ElfHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ExtHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/FatHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/FlvHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/GptHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/HfsHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/IhexHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/LzhHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/MachoHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/MbrHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/MslzHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/MubHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/NtfsHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/PeHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/QcowHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/RpmHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/SquashfsHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/SwfHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/VdiHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/VhdHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/VhdxHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/VmdkHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ApfsHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ApmHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/AvbHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/ComHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Chm/ChmHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/Chm/ChmIn.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/LpHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/LvmHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/SparseHandler.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive/UefiHandler.cpp",

    // CPP/7zip/Compress/ -- Codecs
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Bcj2Coder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Bcj2Register.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BcjCoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BcjRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BitlDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BranchMisc.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BranchRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ByteSwap.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BZip2Crc.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BZip2Decoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BZip2Encoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/BZip2Register.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/CodecExports.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/CopyCoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/CopyRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Deflate64Register.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/DeflateDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/DeflateEncoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/DeflateRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/DeltaFilter.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ImplodeDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ImplodeHuffmanDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzfseDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzhDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Lzma2Decoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Lzma2Encoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Lzma2Register.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzmaDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzmaEncoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzmaRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzmsDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzOutWindow.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/LzxDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/PpmdDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/PpmdEncoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/PpmdRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/PpmdZip.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/QuantumDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Rar1Decoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Rar2Decoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Rar3Decoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Rar3Vm.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/Rar5Decoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/RarCodecsRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ShrinkDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/XpressDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/XzDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/XzEncoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ZDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ZlibDecoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ZlibEncoder.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Compress/ZstdDecoder.cpp",

    // CPP/7zip/Crypto/ -- Crypto codecs
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/7zAes.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/7zAesRegister.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/HmacSha1.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/HmacSha256.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/MyAes.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/MyAesReg.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/Pbkdf2HmacSha1.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/RandGen.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/Rar20Crypto.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/Rar5Aes.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/RarAes.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/WzAes.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/ZipCrypto.cpp",
    "Sources/CSevenZip/vendor/7zip/CPP/7zip/Crypto/ZipStrong.cpp",
]

let package = Package(
    name: "Modules",
    platforms: [ .macOS(.v13) ],
    products: [
        .library(name: "Core", targets: ["Core"]),
        //.library(name: "SevenZipBridge", targets: ["SevenZipBridge"])
    ],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-subprocess.git", from: "0.2.1"),
        .package(url: "https://github.com/kumamotone/XADMasterSwift.git", branch: "main"),
        .package(url: "https://github.com/tsolomko/BitByteData.git", from: "2.0.0"),
        .package(url: "https://github.com/tsolomko/SWCompression.git", from: "4.8.0"),
        .package(url: "https://github.com/tailbeat/TailBeatKit.git", from: "0.10.0")
    ],
    targets: [
        .target(
            name: "Core",
            dependencies: [
                .product(name: "Subprocess", package: "swift-subprocess"),
                .product(name: "XADMasterSwift", package: "XADMasterSwift"),
                "BitByteData",
                "SWCompression",
                .product(name: "TailBeatKit", package: "TailBeatKit"),
                "Swift7zip"
            ],
            resources: [
                .copy("Formats/Catalog.json")
            ]
        ),
        .target(
            name: "CSevenZip",
            path: ".",
            sources: cSevenZipSources + [
                "Sources/CSevenZip/sevenzip_bridge.cpp",
                "Sources/CSevenZip/sevenzip_bridge_write.cpp",
                "Sources/CSevenZip/hw_stubs.c",
            ],
            publicHeadersPath: "Sources/CSevenZip/include",
            cSettings: [
                .define("_7ZIP_ST"),
                .define("_FILE_OFFSET_BITS", to: "64"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/Common"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/Windows"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/7zip"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/7zip/Common"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/C"),
                .headerSearchPath("Sources/CSevenZip"),
                .unsafeFlags(["-w"]),
            ],
            cxxSettings: [
                .define("_7ZIP_ST"),
                .define("_FILE_OFFSET_BITS", to: "64"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/Common"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/Windows"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/7zip"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/7zip/Common"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/CPP/7zip/Archive"),
                .headerSearchPath("Sources/CSevenZip/vendor/7zip/C"),
                .headerSearchPath("Sources/CSevenZip"),
                .unsafeFlags(["-w"]),
            ],
            linkerSettings: [
                .linkedLibrary("c++"),
            ]
        ),
        .target(
            name: "Swift7zip",
            dependencies: ["CSevenZip"],
            path: "Sources/Swift7zip",
            swiftSettings: [
                .swiftLanguageMode(.v6),
            ]
        ),
        .testTarget(
            name: "CoreTests",
            dependencies: [
                "Core",
                "TailBeatKit"
            ],
            resources: [
                .copy("TestArchives/defaultArchives"),
                .copy("TestArchives/lha_lzh"),
                .copy("TestArchives/lzx"),
                .copy("TestArchives/stuffit"),
                .copy("TestArchives/zip")
            ]
        )
    ]
)
